services:
  aftermarket_uat:
    image: techlabscc/internal:aftermarket_invoice_frontend_uat
    container_name: aftermarket-uat
    ports:
      - 1001:1001
    networks:
      - local_network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${PORT}']
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s

  aftermarket_prod:
    image: techlabscc/internal:aftermarket_invoice_frontend_prod
    container_name: aftermarket-production
    ports:
      - 1002:1002
    networks:
      - local_network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${PORT}']
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  local_network:
    external: true
