# syntax=docker/dockerfile:1

ARG NODE_VERSION=20.16.0

## Stage 1: Build
FROM node:${NODE_VERSION}-alpine AS build

WORKDIR /app

# Copy package.json and install dependencies
COPY ./package.json ./
RUN npm install && npm install -g dotenv-cli

# Copy the rest of the application code
COPY . .

# Generate Prisma client and build the application
RUN npm run prisma:generate:test && npm run build:test
###########################################################

## Stage 2: Runtime
FROM node:${NODE_VERSION}-alpine AS runtime

WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=build /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
COPY --from=build /app/.env.test ./.env

# Expose the application port
EXPOSE 1001
ENV PORT=1001
ENV HOSTNAME=0.0.0.0
# Run the application

CMD ["node", "server.js"]
###########################################################
